[colors.primary]
background = "#05182e"
foreground = "#f6dcac"

[colors.selection]
text = "#05182e"
background = "#a7c9c6"

[colors.cursor]
text = "#05182e"
cursor = "#faa968"

[colors.normal]
black = "#303442"
red = "#f85525"
green = "#028391"
yellow = "#e97b3c"
blue = "#faa968"
magenta = "#3f8f8a"
cyan = "#8cbfb8"
white = "#a7c9c6"

[colors.bright]
black = "#134e5a"
red = "#f85525"
green = "#028391"
yellow = "#e97b3c"
blue = "#faa968"
magenta = "#3f8f8a"
cyan = "#8cbfb8"
white = "#f6dcac"
