foreground = #f6dcac
background = #05182e
selection-background = #a7c9c6
selection-foreground = #05182e
cursor-color = #faa968
palette = 0=#303442
palette = 8=#134e5a
palette = 1=#f85525
palette = 9=#f85525
palette = 2=#028391
palette = 10=#028391
palette = 3=#e97b3c
palette = 11=#e97b3c
palette = 4=#faa968
palette = 12=#faa968
palette = 5=#3f8f8a
palette = 13=#3f8f8a
palette = 6=#8cbfb8
palette = 14=#8cbfb8
palette = 7=#a7c9c6
palette = 15=#f6dcac
