[colors.primary]
background = "#000000"
foreground = "#EFEFEF"

[colors.selection]
text = "#000000"
background = "#BEBEBE"

[colors.cursor]
text = "#000000"
cursor = "#E68E0D"

[colors.normal]
black = "#333333"
red = "#D35F5F"
green = "#FFC107"
yellow = "#B91C1C"
blue = "#E68E0D"
magenta = "#D35F5F"
cyan = "#BEBEBE"
white = "#BEBEBE"

[colors.bright]
black = "#8A8A8D"
red = "#B91C1C"
green = "#FFC107"
yellow = "#B90A0A"
blue = "#F59E0B"
magenta = "#B91C1C"
cyan = "#EAEAEA"
white = "#FFFFFF"
