foreground = #100F0F
background = #FFFCF0
selection-background = #B7B5AC
selection-foreground = #FFFCF0
cursor-color = #205EA6
palette = 0=#DAD8CE
palette = 8=#100F0F
palette = 1=#D14D41
palette = 9=#D14D41
palette = 2=#879A39
palette = 10=#879A39
palette = 3=#D0A215
palette = 11=#D0A215
palette = 4=#205EA6
palette = 12=#4385BE
palette = 5=#CE5D97
palette = 13=#CE5D97
palette = 6=#3AA99F
palette = 14=#3AA99F
palette = 7=#B7B5AC
palette = 15=#CECDC3
