[colors.primary]
background = "#181310"
foreground = "#f4f2f1"

[colors.selection]
text = "#181310"
background = "#ded7d3"

[colors.cursor]
text = "#181310"
cursor = "#cf9b68"

[colors.normal]
black = "#181310"
red = "#c0596a"
green = "#cd6a6a"
yellow = "#cf8677"
blue = "#cf9b68"
magenta = "#d6be8f"
cyan = "#cdbc6a"
white = "#ded7d3"

[colors.bright]
black = "#846d62"
red = "#d98291"
green = "#dd7e7e"
yellow = "#e9c1b9"
blue = "#dead7c"
magenta = "#f0e5d1"
cyan = "#ddcd7e"
white = "#f4f2f1"
