foreground = #f4f2f1
background = #181310
selection-background = #ded7d3
selection-foreground = #181310
cursor-color = #cf9b68
palette = 0=#181310
palette = 8=#846d62
palette = 1=#c0596a
palette = 9=#d98291
palette = 2=#cd6a6a
palette = 10=#dd7e7e
palette = 3=#cf8677
palette = 11=#e9c1b9
palette = 4=#cf9b68
palette = 12=#dead7c
palette = 5=#d6be8f
palette = 13=#f0e5d1
palette = 6=#cdbc6a
palette = 14=#ddcd7e
palette = 7=#ded7d3
palette = 15=#f4f2f1
