foreground = #F8FAFC
background = #0F0F14
selection-background = #475569
selection-foreground = #0F0F14
cursor-color = #0EA5E9
palette = 0=#1E293B
palette = 8=#64748B
palette = 1=#EF4444
palette = 9=#EF4444
palette = 2=#10B981
palette = 10=#10B981
palette = 3=#F59E0B
palette = 11=#F59E0B
palette = 4=#0EA5E9
palette = 12=#0EA5E9
palette = 5=#8B5CF6
palette = 13=#8B5CF6
palette = 6=#06B6D4
palette = 14=#06B6D4
palette = 7=#475569
palette = 15=#F8FAFC
