foreground = #bebebe
background = #121212
selection-background = #bebebe
selection-foreground = #121212
cursor-color = #e68e0d
palette = 0=#333333
palette = 8=#8a8a8d
palette = 1=#D35F5F
palette = 9=#B91C1C
palette = 2=#FFC107
palette = 10=#FFC107
palette = 3=#b91c1c
palette = 11=#b90a0a
palette = 4=#e68e0d
palette = 12=#f59e0b
palette = 5=#D35F5F
palette = 13=#B91C1C
palette = 6=#bebebe
palette = 14=#eaeaea
palette = 7=#bebebe
palette = 15=#ffffff
