#!/usr/bin/env bash

# Centralized colors for themes from theme_example_list.txt
# This script generates the app-specific configs for each theme.

THEMES_DIR="${THEMES_DIR:-$HOME/.config/themes}"

generate_theme() {
    local name="$1"
    local bg="$2"
    local fg="$3"
    local c0="$4" c8="$5"
    local c1="$6" c9="$7"
    local c2="$8" c10="$9"
    local c3="${10}" c11="${11}"
    local c4="${12}" c12="${13}"
    local c5="${14}" c13="${15}"
    local c6="${16}" c14="${17}"
    local c7="${18}" c15="${19}"

    local dir="$THEMES_DIR/$name"
    mkdir -p "$dir"

    # Waybar colors.css
    cat > "$dir/waybar.css" <<EOF
@define-color base $bg;
@define-color mantle $c0;
@define-color crust $bg;
@define-color surface0 $c8;
@define-color surface1 $c8;
@define-color surface2 $c7;
@define-color text $fg;
@define-color subtext0 $c7;
@define-color subtext1 $c15;
@define-color blue $c4;
@define-color lavender $c5;
@define-color sapphire $c6;
@define-color sky $c12;
@define-color teal $c6;
@define-color green $c2;
@define-color yellow $c3;
@define-color peach $c11;
@define-color orange $c3;
@define-color maroon $c1;
@define-color red $c1;
@define-color mauve $c13;
@define-color pink $c5;
@define-color flamingo $c1;
@define-color rosewater $c1;
EOF

    # SwayNC colors.css
    cat > "$dir/swaync.css" <<EOF
@define-color bg $bg;
@define-color bg-alt $c0;
@define-color surface $c8;
@define-color surface-alt $c7;
@define-color overlay $c8;
@define-color text $fg;
@define-color text-alt $c7;
@define-color text-dim $c15;
@define-color blue $c4;
@define-color blue-dim $c12;
@define-color cyan $c6;
@define-color purple $c5;
@define-color green $c2;
@define-color yellow $c3;
@define-color orange $c11;
@define-color critical $c1;
@define-color selected $c4;
@define-color border $c4;
@define-color white $c7;
@define-color black $c0;
EOF

    # Ghostty config snippet
    cat > "$dir/ghostty.conf" <<EOF
foreground = $fg
background = $bg
selection-background = $c7
selection-foreground = $bg
cursor-color = $c4
palette = 0=$c0
palette = 8=$c8
palette = 1=$c1
palette = 9=$c9
palette = 2=$c2
palette = 10=$c10
palette = 3=$c3
palette = 11=$c11
palette = 4=$c4
palette = 12=$c12
palette = 5=$c5
palette = 13=$c13
palette = 6=$c6
palette = 14=$c14
palette = 7=$c7
palette = 15=$c15
EOF

    # Alacritty toml
    cat > "$dir/alacritty.toml" <<EOF
[colors.primary]
background = "$bg"
foreground = "$fg"

[colors.selection]
text = "$bg"
background = "$c7"

[colors.cursor]
text = "$bg"
cursor = "$c4"

[colors.normal]
black = "$c0"
red = "$c1"
green = "$c2"
yellow = "$c3"
blue = "$c4"
magenta = "$c5"
cyan = "$c6"
white = "$c7"

[colors.bright]
black = "$c8"
red = "$c9"
green = "$c10"
yellow = "$c11"
blue = "$c12"
magenta = "$c13"
cyan = "$c14"
white = "$c15"
EOF

    # Niri kdl
    cat > "$dir/niri.kdl" <<EOF
layout {
    focus-ring {
        active-color "$c4"
        inactive-color "$c0"
    }
    border {
        active-color "$c4"
        inactive-color "$c0"
    }
}
EOF

    # Fuzzel ini
    # Convert hex to RRGGBBAA (assume FF alpha)
    local bg_hex="${bg#\#}"
    local fg_hex="${fg#\#}"
    local c1_hex="${c1#\#}"
    local c4_hex="${c4#\#}"
    local c7_hex="${c7#\#}"
    
    cat > "$dir/fuzzel.ini" <<EOF
[colors]
background = ${bg_hex}f2
text = ${fg_hex}ff
match = ${c1_hex}ff
selection = ${c7_hex}ff
selection-text = ${bg_hex}ff
selection-match = ${c1_hex}ff
border = ${c4_hex}ff

[main]
match-counter = yes
EOF

    # Hyprlock colors.conf
    # Convert hex to rgba
    local bg_rgba="rgba($(printf "%d, %d, %d" 0x${bg:1:2} 0x${bg:3:2} 0x${bg:5:2}), 1.0)"
    local c4_rgba="rgba($(printf "%d, %d, %d" 0x${c4:1:2} 0x${c4:3:2} 0x${c4:5:2}), 1.0)"
    local fg_rgba="rgba($(printf "%d, %d, %d" 0x${fg:1:2} 0x${fg:3:2} 0x${fg:5:2}), 1.0)"

    cat > "$dir/hyprlock.conf" <<EOF
\$bg = $bg_rgba
\$accent = $c4_rgba
\$text = $fg_rgba
EOF

    # Neovim colors.lua
    cat > "$dir/nvim.lua" <<EOF
return {
    base00 = "$bg",
    base01 = "$c0",
    base02 = "#404040",
    base03 = "#4d4d4d",
    base04 = "$c7",
    base05 = "$fg",
    base06 = "$c7",
    base07 = "$fg",
    base08 = "$c1",
    base09 = "$c9",
    base0A = "$c3",
    base0B = "$c2",
    base0C = "$c6",
    base0D = "$c4",
    base0E = "$c5",
    base0F = "$c13",
}
EOF

    # Neofetch colors.conf
    cat > "$dir/neofetch.conf" <<EOF
# Neofetch theme colors
# Generated by generate_themes.sh
colors=(4 7 7 4 7 7)
ascii_colors=(4)
EOF

    # Fish theme
    cat > "$dir/fish.theme" <<EOF
fish_color_autosuggestion $c8
fish_color_cancel $c1
fish_color_command $c4
fish_color_cwd $c4
fish_color_end $c4
fish_color_error $c1
fish_color_escape $c6
fish_color_gray $c8
fish_color_host $c4
fish_color_host_remote $c2
fish_color_keyword $c1
fish_color_normal $fg
fish_color_operator $c4
fish_color_param $c7
fish_color_quote $c2
fish_color_redirection $fg
fish_color_search_match --background=$c0
fish_color_selection --background=$c8
fish_color_status $c1
fish_color_user $c2
fish_pager_color_completion $fg
fish_pager_color_description $c8
fish_pager_color_prefix $c4
fish_pager_color_progress $c8
EOF

    # Ranger custom.py
    # Convert hex to 256-color approximate (simplified)
    # Since I can't easily calculate 256-color in bash, I'll use placeholders or skip complex mapping
    # Actually, I'll just use a generic template for ranger that uses common color numbers
    cat > "$dir/ranger.py" <<EOF
from ranger.gui.colorscheme import ColorScheme
from ranger.gui.color import *

class Custom(ColorScheme):
    def use(self, context):
        fg, bg, attr = default_colors
        if context.reset: return default_colors
        elif context.in_browser:
            if context.selected: attr = reverse
            if context.directory: fg = 4
            elif context.executable: fg = 2
            if context.link: fg = 6
        elif context.in_titlebar:
            if context.hostname: fg = 1
        return fg, bg, attr
EOF

    # Starship toml palette
    cat > "$dir/starship.toml" <<EOF
[palettes.active]
bg = "$bg"
fg = "$fg"
c0 = "$c0"
c1 = "$c1"
c2 = "$c2"
c3 = "$c3"
c4 = "$c4"
c5 = "$c5"
c6 = "$c6"
c7 = "$c7"
EOF

    # Tmux colors
    cat > "$dir/tmux.conf" <<EOF
set -g status-style "bg=$bg,fg=$fg"
setw -g pane-border-style "fg=$c0"
setw -g pane-active-border-style "fg=$c4"
set -g window-status-current-style "bg=$c4,fg=$bg,bold"
EOF

}

# Themes from theme_example_list.txt
# generate_theme NAME BG FG C0 C8 C1 C9 C2 C10 C3 C11 C4 C12 C5 C13 C6 C14 C7 C15

# Aamis
generate_theme "Aamis" "#0f0f0f" "#eadccc" "#0f0f0f" "#706a6a" "#e25d6c" "#e9838f" "#cea37f" "#cea37f" "#f4bb54" "#edb95a" "#e2be8a" "#eacea7" "#ede4c8" "#ede4c8" "#e8ab3b" "#ecb95c" "#e6caab" "#eadccc"

# Brutalism
generate_theme "Brutalism" "#121212" "#ded3d3" "#121212" "#b89494" "#450404" "#9c0909" "#630a0a" "#9f1d1d" "#cc7a7a" "#e7baba" "#ce5757" "#e96565" "#c87777" "#e28585" "#d48484" "#eb9696" "#d1c7c7" "#ded3d3"

# CopperNight (Parsing from the list)
generate_theme "CopperNight" "#11111b" "#e6e6e6" "#1e1e2e" "#585b70" "#f38ba8" "#f38ba8" "#a6e3a1" "#a6e3a1" "#f9e2af" "#fab387" "#89b4fa" "#89b4fa" "#cba6f7" "#cba6f7" "#94e2d5" "#94e2d5" "#bac2de" "#a6adc8"

# Flexoki_dark
generate_theme "Flexoki_dark" "#100F0F" "#CECDC3" "#100F0F" "#6F6E69" "#AF3029" "#D14D41" "#66800B" "#879A39" "#AD8301" "#D0A215" "#205EA6" "#4385BE" "#A02F6F" "#CE5D97" "#24837B" "#3AA99F" "#878580" "#CECDC3"

# Glory-Antic
generate_theme "Glory-Antic" "#181310" "#f4f2f1" "#181310" "#846d62" "#c0596a" "#d98291" "#cd6a6a" "#dd7e7e" "#cf8677" "#e9c1b9" "#cf9b68" "#dead7c" "#d6be8f" "#f0e5d1" "#cdbc6a" "#ddcd7e" "#ded7d3" "#f4f2f1"

# HarborDark
generate_theme "HarborDark" "#1B1B1B" "#efebdc" "#1B1B1B" "#817f68" "#F44336" "#f44336" "#e75a50" "#e75a50" "#a99b7a" "#a99b7a" "#e58980" "#e58980" "#77838a" "#77838a" "#6d6d6d" "#6d6d6d" "#E1CE98" "#efebdc"

# Midnight (Approximate palette from list)
generate_theme "Midnight" "#000000" "#EFEFEF" "#333333" "#8A8A8D" "#D35F5F" "#B91C1C" "#FFC107" "#FFC107" "#B91C1C" "#B90A0A" "#E68E0D" "#F59E0B" "#D35F5F" "#B91C1C" "#BEBEBE" "#EAEAEA" "#BEBEBE" "#FFFFFF"

# Latchdark
generate_theme "Latchdark" "#151515" "#edecec" "#151515" "#c7c5c5" "#9a8e8e" "#c6bebe" "#a19696" "#cdc6c6" "#9d9393" "#b5aeae" "#aca3a3" "#c4bebe" "#bab3b3" "#d2cece" "#c9c3c3" "#e1dede" "#E1DEDE" "#edecec"

# Oasis
generate_theme "Oasis" "#000000" "#FAF7F0" "#000000" "#666666" "#D06666" "#FFA0A0" "#53D390" "#96EA7F" "#F0E68C" "#FFA247" "#519BFF" "#87CEEB" "#C28EFF" "#D2ADFF" "#5ABAAE" "#8FD1C7" "#DDDBD5" "#FFF9F2"

# FluidGlass (Approximate from description)
generate_theme "FluidGlass" "#0F0F14" "#F8FAFC" "#1E293B" "#64748B" "#EF4444" "#EF4444" "#10B981" "#10B981" "#F59E0B" "#F59E0B" "#0EA5E9" "#0EA5E9" "#8B5CF6" "#8B5CF6" "#06B6D4" "#06B6D4" "#475569" "#F8FAFC"

# --- Omarchy Default Themes (Auto-Generated) ---
generate_theme "Tokyo Night" "#1a1b26" "#a9b1d6" "#32344a" "#444b6a" "#f7768e" "#ff7a93" "#9ece6a" "#b9f27c" "#e0af68" "#ff9e64" "#7aa2f7" "#7da6ff" "#ad8ee6" "#bb9af7" "#449dab" "#0db9d7" "#787c99" "#acb0d0"
generate_theme "Catppuccin" "#1e1e2e" "#cdd6f4" "#45475a" "#585b70" "#f38ba8" "#f38ba8" "#a6e3a1" "#a6e3a1" "#f9e2af" "#f9e2af" "#89b4fa" "#89b4fa" "#f5c2e7" "#f5c2e7" "#94e2d5" "#94e2d5" "#bac2de" "#a6adc8"
generate_theme "Lumon" "#16242d" "#d6e2ee" "#1b2d40" "#304860" "#4d86b0" "#73a6cb" "#5e95bc" "#86b7d8" "#6fa4c9" "#9dcae5" "#6fb8e3" "#f2fcff" "#8bc9eb" "#b1d8ee" "#b4e4f6" "#d1eef8" "#d6e2ee" "#ffffff"
generate_theme "Ethereal" "#060B1E" "#ffcead" "#3C486D" "#6d7db6" "#ED5B5A" "#faaaa9" "#92a593" "#c4cfc4" "#E9BB4F" "#f7dc9c" "#7d82d9" "#c2c4f0" "#c89dc1" "#ead7e7" "#a3bfd1" "#dfeaf0" "#F99957" "#ffcead"
generate_theme "Everforest" "#2d353b" "#d3c6aa" "#475258" "#475258" "#e67e80" "#e67e80" "#a7c080" "#a7c080" "#dbbc7f" "#dbbc7f" "#7fbbb3" "#7fbbb3" "#d699b6" "#d699b6" "#83c092" "#83c092" "#d3c6aa" "#d3c6aa"
generate_theme "Gruvbox" "#282828" "#d4be98" "#3c3836" "#3c3836" "#ea6962" "#ea6962" "#a9b665" "#a9b665" "#d8a657" "#d8a657" "#7daea3" "#7daea3" "#d3869b" "#d3869b" "#89b482" "#89b482" "#d4be98" "#d4be98"
generate_theme "Miasma" "#222222" "#c2c2b0" "#000000" "#666666" "#685742" "#685742" "#5f875f" "#5f875f" "#b36d43" "#b36d43" "#78824b" "#78824b" "#bb7744" "#bb7744" "#c9a554" "#c9a554" "#d7c483" "#d7c483"
generate_theme "Hackerman" "#0B0C16" "#ddf7ff" "#3E4058" "#6a6e95" "#50f872" "#85ff9d" "#4fe88f" "#9cf7c2" "#50f7d4" "#a4ffec" "#829dd4" "#c4d2ed" "#86a7df" "#cddbf4" "#7cf8f7" "#d1fffe" "#85E1FB" "#ddf7ff"
generate_theme "Osaka Jade" "#111c18" "#C1C497" "#23372B" "#53685B" "#FF5345" "#db9f9c" "#549e6a" "#63b07a" "#459451" "#E5C736" "#509475" "#ACD4CF" "#D2689C" "#75bbb3" "#2DD5B7" "#8CD3CB" "#F6F5DD" "#9eebb3"
generate_theme "Kanagawa" "#1f1f28" "#dcd7ba" "#090618" "#727169" "#c34043" "#e82424" "#76946a" "#98bb6c" "#c0a36e" "#e6c384" "#7e9cd8" "#7fb4ca" "#957fb8" "#938aa9" "#6a9589" "#7aa89f" "#c8c093" "#dcd7ba"
generate_theme "Nord" "#2e3440" "#d8dee9" "#3b4252" "#4c566a" "#bf616a" "#bf616a" "#a3be8c" "#a3be8c" "#ebcb8b" "#ebcb8b" "#81a1c1" "#81a1c1" "#b48ead" "#b48ead" "#88c0d0" "#8fbcbb" "#e5e9f0" "#eceff4"
generate_theme "Matte Black" "#121212" "#bebebe" "#333333" "#8a8a8d" "#D35F5F" "#B91C1C" "#FFC107" "#FFC107" "#b91c1c" "#b90a0a" "#e68e0d" "#f59e0b" "#D35F5F" "#B91C1C" "#bebebe" "#eaeaea" "#bebebe" "#ffffff"
generate_theme "Vantablack" "#000000" "#ffffff" "#404040" "#5c5c5c" "#a4a4a4" "#a4a4a4" "#b6b6b6" "#b6b6b6" "#cecece" "#cecece" "#8d8d8d" "#8d8d8d" "#9b9b9b" "#9b9b9b" "#b0b0b0" "#b0b0b0" "#ececec" "#ffffff"
generate_theme "Ristretto" "#2c2525" "#e6d9db" "#72696a" "#948a8b" "#fd6883" "#ff8297" "#adda78" "#c8e292" "#f9cc6c" "#fcd675" "#f38d70" "#f8a788" "#a8a9eb" "#bebffd" "#85dacc" "#9bf1e1" "#e6d9db" "#f1e5e7"
generate_theme "Retro 82" "#05182e" "#f6dcac" "#303442" "#134e5a" "#f85525" "#f85525" "#028391" "#028391" "#e97b3c" "#e97b3c" "#faa968" "#faa968" "#3f8f8a" "#3f8f8a" "#8cbfb8" "#8cbfb8" "#a7c9c6" "#f6dcac"
generate_theme "Flexoki Light" "#FFFCF0" "#100F0F" "#DAD8CE" "#100F0F" "#D14D41" "#D14D41" "#879A39" "#879A39" "#D0A215" "#D0A215" "#205EA6" "#4385BE" "#CE5D97" "#CE5D97" "#3AA99F" "#3AA99F" "#B7B5AC" "#CECDC3"
generate_theme "Rose Pine" "#faf4ed" "#575279" "#f2e9e1" "#9893a5" "#b4637a" "#b4637a" "#286983" "#286983" "#ea9d34" "#ea9d34" "#56949f" "#56949f" "#907aa9" "#907aa9" "#d7827e" "#d7827e" "#575279" "#575279"
generate_theme "Catppuccin Latte" "#eff1f5" "#4c4f69" "#bcc0cc" "#acb0be" "#d20f39" "#d20f39" "#40a02b" "#40a02b" "#df8e1d" "#df8e1d" "#1e66f5" "#1e66f5" "#ea76cb" "#ea76cb" "#179299" "#179299" "#5c5f77" "#6c6f85"
generate_theme "White" "#ffffff" "#000000" "#c0c0c0" "#c0c0c0" "#2a2a2a" "#2a2a2a" "#3a3a3a" "#3a3a3a" "#4a4a4a" "#4a4a4a" "#1a1a1a" "#1a1a1a" "#2e2e2e" "#2e2e2e" "#3e3e3e" "#3e3e3e" "#000000" "#000000"
