# Fuzzel — fuzzel.ini
# Abhijeet - TokyoNight Night
# Docs: man fuzzel.ini

[main]
font         = JetBrainsMono Nerd Font:size=14
dpi-aware    = no
prompt       = "❯ "
icons-enabled = yes
show-actions = yes
match-mode   = fuzzy
lines        = 10
width        = 40
horizontal-pad = 40
vertical-pad   = 25
inner-pad      = 15
terminal     = ghostty
layer        = overlay
exit-on-lost-focus = yes

[border]
width  = 2
radius = 12

[key-bindings]
cancel         = Escape
next           = Down Control+n
prev           = Up Control+p
delete-prev    = BackSpace
delete-next    = Delete
delete-line-backward = Control+u

# Colors will be appended by theme-changer.sh

